---
title: "Setup"
author: "Phil Farrell"
date: "20 December 2016"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <- c("readr", "dplyr", "plyr", "tidyr", "ggplot2", "stringr", "lubridate", "sqldf", "randomNames", "data.table", "devtools", "scales", "knitr", "xtable", "stringi")

p <- installed.packages()

#install.packages(pkgs = packages[!(packages %in% row.names(p))])

library(devtools)

ifelse(!("rCharts" %in% row.names(p)), install_github('ramnathv/rCharts'), TRUE)

library(Enquiries)
#library(ABR)
library(rCharts)

lapply(packages, require, character.only = TRUE)

```

```{r load, message=FALSE, warning=FALSE, include=FALSE}

CallQual <- read_delim("N:/ABR/GENTRACK DATA/data AGAIN  for phil 22 nov.txt", 
                    delim = "|", quote = "") #quote = "" is important to avoid parsing failures

```

```{r organise memo information, message=FALSE, warning=FALSE, include=FALSE}

filter <- !(as.numeric(row.names(CallQual)) %in% problems(CallQual)$row)

CallQual2 <- CallQual[filter,]

names <- unique(randomNames(n = 2000000, which.names = "first"))

Clean <- function(CallQual) { 
    
    ##Create the Enquiry column
  
    CallQual$ENQUIRY <- ""
    
    p.1 <- "(.[^=]*)=(.[^-]*)"
    idx <- grepl(p.1, CallQual$MEMO_POS1)
    CallQual$ENQUIRY[idx] <- gsub(p.1, "\\2",  CallQual$MEMO_POS1[idx])
    
    p.2 <- "(.[^=]*):"
    idx <- grepl(p.2, CallQual$MEMO_POS1)
    #CallQual$ENQUIRY[idx] <- gsub(p.2, "\\2",  CallQual$MEMO_POS1[idx])
    CallQual$ENQUIRY[idx] <- paste(CallQual$MEMO_POS1[idx], CallQual$MEMO_POS2[idx]) 
    
    id <- logical(length(CallQual$ENQUIRY[idx]))
    
    id[grepl("bill", CallQual$ENQUIRY[idx])] <- "ACCOUNT INFORMATION"
    id[grepl("leak", CallQual$ENQUIRY[idx])] <- "METERING"
    id[grepl("update my details", CallQual$ENQUIRY[idx])] <- "ACCOUNT MAINTENANCE"
    id[grepl("payment arrangement", CallQual$ENQUIRY[idx])] <- "PAYMENTS"
    id[grepl("payment[^arrangement]", CallQual$ENQUIRY[idx])] <- "PAYMENTS"
    id[grepl("disconnection and reconnection", CallQual$ENQUIRY[idx])] <- "Water Serv Rbty"
    id[grepl("change the details", CallQual$ENQUIRY[idx])] <- "ACCOUNT MAINTENANCE"
    id[grepl("deceased", CallQual$ENQUIRY[idx])] <- "OWNER"
    id[grepl("final notice", CallQual$ENQUIRY[idx])] <- "ISSUE BILL"
    id[grepl("pension", CallQual$ENQUIRY[idx])] <- "CONCESSIONS & REBATES"
    id[grepl("no longer occupy", CallQual$ENQUIRY[idx])] <- "TENANCY"
    CallQual$ENQUIRY[idx][id == "FALSE"] <- "OTHER"
    
    CallQual$ENQUIRY[idx] <- id
    
    p.3 <- "(.*)-(.*)"
    idx <- grepl(p.3, CallQual$ENQUIRY)
    CallQual$ENQUIRY[idx] <- gsub(p.3, "\\1", CallQual$ENQUIRY[idx])
    
    enquiry <- unique(CallQual$ENQUIRY)
    
    idx <- lapply(enquiry, function(x) which(grepl(x, enquiry[-which(enquiry == x)]) == TRUE) + 1)
    
    names(idx) <- enquiry
    
    idx <- idx[lapply(idx, length) > 0]
    
    idx <- lapply(idx, function(x) which(grepl(paste(enquiry[x], collapse = "|"), CallQual$ENQUIRY)))
    
    lapply(names(idx), function(i) CallQual$ENQUIRY[idx[[i]]] <<- i)
    
    split <- strsplit(enquiry, "\\W+")
    
    if(length(CallQual[CallQual$ENQUIRY == "CUSTOMER CORRESPONDENCDE",]$ENQUIRY != 0)) {
    
      CallQual[CallQual$ENQUIRY == "CUSTOMER CORRESPONDENCDE",]$ENQUIRY <- "CUSTOMER CORRESPONDENCE"
      
    }
    
    # idx <- lapply(split, function(x) any(tolower(x) == tolower(names)))
    
    # wordcount <- vapply(split, length, integer(1))
    # 
    # keys <- enquiry[wordcount <= 5]
    # 
    # CallQual$ENQUIRY <- str_trim(CallQual$ENQUIRY)
    # 
    # lapply(seq_along(idx), function(i) keys[unlist(idx[i])] <- keys[i])
    # 
    # keys <- keys[!tolower(keys) %in% tolower(names)]
    # 
    # id <- !(CallQual$RESULT %in% keys)
    # 
    # CallQual$MEMO_POS2[id] <- str_trim(paste(CallQual$MEMO_POS2[id], CallQual$RESULT[id], sep = " "))
    
    # CallQual$RESULT[id] <- ""
    
    ## Create the action column
    CallQual$ACTION <- ""
    
    fix <- "(-|not|payment)$"
    idx <- grepl(fix, CallQual$MEMO_POS2)
    
    CallQual$MEMO_POS2[idx] <- paste(CallQual$MEMO_POS2[idx], CallQual$MEMO_POS3[idx])
    
    CallQual$MEMO_POS3[idx] <- ""
    
    fix <- "re-send"
    idx <- grepl(fix, CallQual$MEMO_POS2, ignore.case = TRUE)
    
    CallQual$MEMO_POS2[idx] <- gsub("re-send", "resend", CallQual$MEMO_POS2[idx], ignore.case = TRUE)
    
    p.1 <- "(.[^=]*)=(.[^-]*)-(.[^-]*)-(.[^-]*)"
    idx.1 <- grepl(p.1, CallQual$MEMO_POS2)  
    
    CallQual$ACTION[idx.1] <- gsub(p.1, "\\2 \\3", CallQual$MEMO_POS2[idx.1]) 
    
    p.2 <- "(.[^=]*)=(.[^-]*)-(.[^-]*)"
    idx.2 <- grepl(p.2, CallQual$MEMO_POS2)  
    
    CallQual$ACTION[idx.2 & !idx.1] <- gsub(p.2, "\\2", CallQual$MEMO_POS2[idx.2 & !idx.1]) 
    
    p.3 <- "(.[^=]*)=(.[^-]*)"
    idx.3 <- grepl(p.3, CallQual$MEMO_POS2)  
    
    CallQual$ACTION[idx.3 & !idx.2 & !idx.1] <- gsub(p.3, "\\2", CallQual$MEMO_POS2[idx.3 & !idx.2 & !idx.1]) 
    
    #Clean the action column
    
    CallQual$ACTION <- str_trim(CallQual$ACTION)
    
    action <- unique(CallQual$ACTION)
    
    split <- strsplit(action, "\\W+")
    
    wordcount <- vapply(split, length, integer(1))
    
    action <- action[wordcount >= 3]
    
    idx <- lapply(action, function(x) which(grepl(x, action) == TRUE))
    
    names(idx) <- action
    
    idx <- idx[lapply(idx, length) > 1]
    
    idx <- lapply(idx, function(x) action[x])
    
    lapply(names(idx), function(i) CallQual$ACTION[CallQual$ACTION %in% idx[[i]]] <<- i)
    
    idx <- lapply(idx, function(x) which(grepl(paste(action[x], collapse = "|"), CallQual$ACTION)))
    
    lapply(names(idx), function(i) CallQual$ACTION[idx[[i]]] <<- i)
    
    action <- unique(CallQual$ACTION)
    
    split <- strsplit(tolower(action), "\\W+")
    
    wordcount <- vapply(split, length, integer(1))
    
    keys <- action[wordcount >= 7]
    
    filter <- split[wordcount >= 7]
    
    idx <- keys[unlist(lapply(filter, function(x) any((x %in% tolower(names) == TRUE))))]
    
    idx2 <- lapply(action, function(x) which(grepl(x, idx[x != idx]) == TRUE))
    
    names(idx2) <- action
    
    idx2 <- idx2[lapply(idx2, length) > 0 & names(idx2) != ""]
    
    idx3 <- ldply(idx2, function(x) idx[x]) %>%
            group_by(V1) %>%
            filter(.id == .id[which.max(nchar(.id))]) %>%
            ungroup()
    
    lapply(1:nrow(idx3), function(i) CallQual$ACTION[CallQual$ACTION == idx3$V1[i]] <<- idx3$.id[i])
    
    unknown <- idx[!(idx %in% idx3$V1)]
    
    lapply(seq_along(unknown), function(i) CallQual$ACTION[CallQual$ACTION == unknown[i]] <<- "")
    
    # action <- unique(CallQual$ACTION)
    # 
    # split <- strsplit(tolower(action), "\\W+")
    # 
    # wordcount <- vapply(split, length, integer(1))
    # 
    # keys <- action[wordcount >= 8]
    # 
    # id <- !(CallQual$RESULT %in% keys)
    # 
    # CallQual$MEMO_POS2[id] <- str_trim(paste(CallQual$MEMO_POS2[id], CallQual$RESULT[id], sep = " "))
    # 
    # CallQual$RESULT[id] <- ""
    
    ##Create the result column
    CallQual$RESULT <- ""
    
    p.1 <- "(.[^=]*)=(.[^-]*)-(.[^-]*)-(.[^-]*)"
    idx.1 <- grepl(p.1, CallQual$MEMO_POS2)  
    
    CallQual$RESULT[idx.1] <- gsub(p.1, "\\4", CallQual$MEMO_POS2[idx.1]) 
    
    p.2 <- "(.[^=]*)=(.[^-]*)-(.[^-]*)"
    idx.2 <- grepl(p.2, CallQual$MEMO_POS2)  
    
    CallQual$RESULT[idx.2 & !idx.1] <- gsub(p.2, "\\3", CallQual$MEMO_POS2[idx.2 & !idx.1]) 
    
    p.3 <- "(.[^=]*)=(.[^-]*)"
    idx.3 <- grepl(p.3, CallQual$MEMO_POS2)  
    
    CallQual$RESULT[idx.3 & !idx.2 & !idx.1] <- ""
    
    CallQual$RESULT <- str_trim(CallQual$RESULT)
    
    #Clean the result column
    result <- unique(CallQual$RESULT)
    finalised <- paste(result[grepl("^f[^o].*", result, ignore.case = TRUE)], collapse = "|")
    id <- grepl(finalised, CallQual$RESULT, ignore.case = TRUE) 
    CallQual$RESULT[id] <- gsub(finalised, "Finalised", CallQual$RESULT[id], ignore.case = TRUE)
    
    result <- unique(CallQual$RESULT)
    referred <- paste(result[grepl("^ref.*[^L]$", result, ignore.case = TRUE)], collapse = "|")
    id <- grepl(referred, CallQual$RESULT, ignore.case = TRUE) 
    CallQual$RESULT[id] <- gsub(referred, "Referred", CallQual$RESULT[id], ignore.case = TRUE)
    
    result <- unique(CallQual$RESULT)
    crel <- paste(result[grepl("^ref.*[L]$", result, ignore.case = TRUE)], collapse = "|")
    id <- grepl(crel, CallQual$RESULT, ignore.case = TRUE) 
    CallQual$RESULT[id] <- gsub(crel, "ReferredCREL", CallQual$RESULT[id], ignore.case = TRUE)
    
    result <- unique(CallQual$RESULT)
    
    split <- strsplit(result, "\\W+")
    
    wordcount <- vapply(split, length, integer(1))
    
    keys <- result[wordcount <= 2]
    
    keys <- keys[!tolower(keys) %in% tolower(names)]
    
    id <- !(CallQual$RESULT %in% keys)
    
    CallQual$MEMO_POS2[id] <- str_trim(paste(CallQual$MEMO_POS2[id], CallQual$RESULT[id], sep = " "))
    
    CallQual$RESULT[id] <- ""
    
    CallQual[,17:24][is.na(CallQual[,17:24])] <- ""
    
    idx <- grepl("[0-9]+/[0-9]+/[0-9]+", CallQual$USES)
    
    idx.2 <- !is.na(CallQual$MEMO_POS10)
    
    CallQual[idx & idx.2,]$MEMO_POS9 <- paste(CallQual[idx & idx.2,]$MEMO_POS9, CallQual[idx & idx.2,]$MEMO_POS10)
    
    CallQual[idx,25:33] <- CallQual[idx,26:34]
    
    idx <- !grepl("^RES|^NONRES", CallQual$USES)
    
    idx.2 <- !is.na(CallQual$MEMO_POS10)
    
    CallQual[idx & idx.2,]$MEMO_POS9 <- paste(CallQual[idx & idx.2,]$MEMO_POS9, CallQual[idx & idx.2,]$MEMO_POS10)
    
    CallQual[idx,25:33] <- CallQual[idx,26:34]
    
    CallQual <- CallQual %>%
                 mutate(MEMO = paste(MEMO_POS3, 
                                    MEMO_POS4,
                                    MEMO_POS5,
                                    MEMO_POS6,
                                    MEMO_POS7,
                                    MEMO_POS8,
                                    MEMO_POS9,
                                    MEMO_POS10,
                                    sep = " "))
    
    
    
    
return(CallQual)
}

CallQual3 <- Clean(CallQual2) #to do: need to fix ENQUIRY = FALSE#

rm(CallQual2)

cols <- vapply(CallQual3, is.character, logical(1))

CallQual3[ , cols] <- apply(CallQual3[ , cols], 2, str_trim)
CallQual3[ , cols] <- apply(CallQual3[ , cols], 2, toupper)

```

```{r Date time, message=FALSE, warning=FALSE, include=FALSE}

CallQual3 <- CallQual3 %>%
                    mutate(SRM = ifelse(!is.na(SR_SERV_CODE), TRUE, FALSE),
                    MEMO_DATETIME = parse_date_time(MEMO_DATETIME, orders="%d-%m-%y %H:%M:%S"),
                    SR_DATETIME = parse_date_time(SR_DATETIME, orders="%d-%m-%y %H:%M:%S"),
                    CUS_BIRTHDATE = dmy(format(CUS_BIRTHDATE, format="%d/%m/%y")),
                    STAT_DATE = dmy(format(STAT_DATE, format="%d/%m/%y")))

```

```{r Key Accounts, message=FALSE, warning=FALSE, include=FALSE}
PropertyLayer <- read.csv("file:///N:/KarlBlackhall/Gentrack AL/PROPERTY_LAYER_1516FY (Q1-Q4).csv",
                          stringsAsFactors = FALSE) %>%
                 mutate(ACC_NAME = gsub("[[:space:]]|[^[:alnum:]]", "", ACCOUNT_NAME))

KeyAccounts <- read.csv("file:///C:/Enquiries/data/KeyAccounts.csv",
                        stringsAsFactors = FALSE) %>%
               mutate(ACCOUNT_NAME = str_trim(gsub("(.+)(\\(.+)", "\\1", Key.Customer))) %>%
               select(ACCOUNT_NAME)


KeyAccountsName <- unique(gsub("[[:space:]]|[^[:alnum:]]", "", KeyAccounts$ACCOUNT_NAME))

link <- lapply(KeyAccountsName, function(x) PropertyLayer$MASTERID[which(grepl(x, PropertyLayer$ACC_NAME, ignore.case = TRUE) == TRUE)])

KeyAccountsID <- data.frame(MASTERID = unlist(link)) %>%
                 left_join(select(PropertyLayer, MASTERID, ACCOUNT_NAME)) %>%
                 distinct()

write.csv(KeyAccountsID, "C:/Enquiries/data/KeyAccountsID.csv")

KeyAccountsID <- read.csv("C:/Enquiries/data/KeyAccountsID.csv")

CallQual3$KEY_ACCOUNT <- "KEY_ACCOUNT"

CallQual3[!(as.numeric(substr(CallQual3$MEMO_CONSUMER, 3, 9)) %in% KeyAccountsID),]$KEY_ACCOUNT <- "NON_KEY"

```

```{r Gentrack Acc type, message=FALSE, warning=FALSE, include=FALSE}

CallQual3$ACC_TYPE <- "TENANT"

CallQual3[substr(CallQual3$MEMO_CONSUMER, 1, 2) == 12,]$ACC_TYPE <- "OWNER"

CallQual3[substr(CallQual3$MEMO_CONSUMER, 1, 2) == 32,]$ACC_TYPE <- "TRADE_WASTE"

CallQual3[substr(CallQual3$MEMO_CONSUMER, 1, 2) == 99,]$ACC_TYPE <- "99"

CallQual3[substr(CallQual3$MEMO_CONSUMER, 1, 2) == 99,]$ACC_TYPE <- "99"

```

```{r PostgreSQL connect, message=FALSE, warning=FALSE, include=FALSE}

PostgreSQLconnect <- function(dbname = "ABRdb", type = 1, user = NULL, host = NULL) {

  if(!require(RPostgreSQL)) {
    message("installing the 'RPostgreSQL' package")
    install.packages("RPostgreSQL")
  }

  system("C:/bin/pgsql/run.bat")

  Sys.sleep(3)

  # Case 1: local database not requiring username/password
  if(type == 1) {

    con <- dbConnect(dbDriver("PostgreSQL"), dbname=dbname)
  }

  # Case 2: local database requiring username/password
  else if(type == 2) {

    con <- dbConnect(dbDriver("PostgreSQL"), user=user,
                     password=scan(what=character(),nmax=1,quiet=TRUE), dbname=dbname)
  }


  # Case 3: remote database requiring username/password
  else {
    con <- dbConnect(dbDriver("PostgreSQL"), user=user,
                     password=scan(what=character(),nmax=1,quiet=TRUE), dbname=dbname, host=host)
  }

  return(con)

}

conn <- PostgreSQLconnect()

```

```{r Write CAllQual3 to PGSQL, message=FALSE, warning=FALSE, include=FALSE}

dbRemoveTable(conn, "CallQual3")

dbWriteTable(con=conn,
             name="CallQual3",
             value=CallQual3,
             row.names=FALSE,
             append=FALSE)

```

